enfermedades = {1:"Ciertas enfermedades infecciosas y parasitarias",
                2:"Tumores [neoplasias]",
                3:"Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos transtornos que afectan el mecanismo de la inmunidad",
                4:"Enfermedades endocrinas, nutricionales y metabólicas",
                5:"Transtornos mentales y del comportamiento",
                6:"Enfermedades del sistema nervioso",
                7:"Enfermedades del ojo y sus anexos",
                8:"Enfermedades del oído y de la apófisis mastoides",
                9:"Enfermedades del sistema circulatorio",
                10:"Enfermedades del sistema respiratorio",
                11:"Enfermedades del sistema digestivo",
                12:"Enfermedades de la piel y del tejido subcutáneo",
                13:"Enfermedades del sistema osteomuscular y del tejido conjuntivo",
                14:"Enfermedades del sistema genitourinario",
                15:"Embarazo, parto y puerperio",
                16:"Ciertas afecciones originadas en el período perinatal",
                17:"Malformaciones congénitas, deformaciones y anomalías cromosómicas",
                18:"Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte",
                19:"Traumatismos, envenenamientos y algunas otras consecuencias de causas externas",
                20:"Causas externas de morbilidad y de mortalidad",
                21:"Factores que influyen en el estado de salud y contacto con los servicios de salud",
                22:"Códigos para propósitos especiales"}

print (enfermedades)